set nocompatible
set tabstop=2
set shiftwidth=2
set number
set ls=2
set ruler
set history=50
set backspace=indent,eol,start
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/vimswap
syntax on
